name: Build Node JS App without cache

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache-dependency-path: app/package-lock.json
          cache: npm
      - name: Run build
        run: npm ci
      - name: Run Build
        run: npm run build --if-present
