name: Conditional Workflow

on:
    workflow_dispatch: 
    push:
        branches:
            - main
    
jobs:
    random-number-generator:
        runs-on: ubuntu-latest
        outputs:
            random-number: ${{ steps.generate-random-number.outputs.number}}
        steps:
            - id: generate-random-number
              run: echo "number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
    
    consumer-of-generator:
        needs: random-number-generator
        runs-on: ubuntu-latest
        steps:
            - run: echo "Random number is ${{ needs.random-number-generator.outputs.random-number }}"