name: Conditional Workflow

on:
    workflow_dispatch: 
    push:
        branches:
            - main
    
jobs:
    test-github-outputs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - id: generate-number
              run: echo "number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
            - id: use-number
              run: echo "The number is ${{ steps.generate-number.outputs.number }}"